project 'JustTest/JustTest.xcworkspace'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'JustTest' do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage','~> 4.1.2'
pod 'FMDB','~> 2.7.2'
pod 'Masonry', '~> 1.1.0'
pod 'JSONModel', '~> 1.7.0'
end
